apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-depl
  name: mealie-depl
  namespace: mealie
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie-depl
  type: LoadBalancer
