apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-depl
  name: mealie-depl
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-depl
  template:
    metadata:
      labels:
        app: mealie-depl
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.0.0
        name: mealie
        volumeMounts:
          - name: mealie-data
            mountPath: /app/data
        ports:
          - containerPort: 9000
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
